### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by fuya417061649** [vectorisvector/inscription#6]
![1702525384403](https://github.com/vectorisvector/Polaris/assets/90825234/ab9c2366-4aa0-410c-8d81-e6ce7689deb2)
ReferenceError: Request is not defined
    at Object.<anonymous> (D:\Polaris\node_modules\_next@14.0.3@next\dist\server\web\spec-extension\request.js:28:27)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.mod.require (D:\Polaris\node_modules\_next@14.0.3@next\dist\server\require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Polaris\node_modules\_next@14.0.3@next\dist\server\web\spec-extension\adapters\next-request.js:37:18)

**Comment by lhl-cpu** [comment]
It is working with both 18.17 and 20.9.0 for me; node.js version.
